// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceMissionsTracker.Infrastructure.DatabaseContext;

#nullable disable

namespace SpaceMissionsTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SpaceMissionsTrackerDbContext))]
    [Migration("20260403003030_AddAstronautsTable")]
    partial class AddAstronautsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceMissionsTracker.Core.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Founded")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Founded = 1958,
                            Name = "NASA"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Europe",
                            Founded = 1975,
                            Name = "ESA"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Russia",
                            Founded = 1992,
                            Name = "Roscosmos"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Founded = 2002,
                            Name = "SpaceX"
                        });
                });

            modelBuilder.Entity("SpaceMissionsTracker.Core.Entities.Astronaut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Astronauts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1930,
                            Name = "Neil Armstrong",
                            Nationality = "USA"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1930,
                            Name = "Buzz Aldrin",
                            Nationality = "USA"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1934,
                            Name = "Yuri Gagarin",
                            Nationality = "USSR"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1951,
                            Name = "Sally Ride",
                            Nationality = "USA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
